/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tab_main;

import dangnhap_dangky.login_admin;
import dangnhap_dangky.login_staff;

/**
 *
 * @author Dell
 */
public class phanquyennguoidung extends javax.swing.JFrame {

    /**
     * Creates new form phanquyennguoidung
     */
    public phanquyennguoidung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_staff = new javax.swing.JToggleButton();
        button_admin = new javax.swing.JToggleButton();
        labelthongbao = new javax.swing.JLabel();
        backgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quan ly kho");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_staff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_staff.setText("Nhân viên");
        button_staff.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEtchedBorder()));
        button_staff.setContentAreaFilled(false);
        button_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_staffActionPerformed(evt);
            }
        });
        getContentPane().add(button_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 190, 140));

        button_admin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_admin.setText("Quản trị viên");
        button_admin.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEtchedBorder()));
        button_admin.setContentAreaFilled(false);
        button_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_adminActionPerformed(evt);
            }
        });
        getContentPane().add(button_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, 140));

        labelthongbao.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        labelthongbao.setText("Chọn quyền hạn của bạn");
        getContentPane().add(labelthongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 410, 70));

        backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagine/background.jpg"))); // NOI18N
        getContentPane().add(backgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_adminActionPerformed
        // TODO add your handling code here:
        new login_admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_adminActionPerformed

    private void button_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_staffActionPerformed
        // TODO add your handling code here:
        new login_staff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_staffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(phanquyennguoidung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(phanquyennguoidung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(phanquyennguoidung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(phanquyennguoidung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new phanquyennguoidung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgound;
    private javax.swing.JToggleButton button_admin;
    private javax.swing.JToggleButton button_staff;
    private javax.swing.JLabel labelthongbao;
    // End of variables declaration//GEN-END:variables
}
